[project]
name="Project Manager"
version="0.0.0"
edition="0.0.0"

[[todo]]
name="upgrade system"
priority=0.3
difficulty=1.0


[[todo]]
name="cli system"
priority=0.8
difficulty=0.5

[[todo]]
name="project status"
priority=0.1
difficulty=0.1

[[todo.subfeature]]
name="calculate % done"
priority=0.4
difficulty=0.1

[[done]]
name="read project"
priority=1.0
difficulty=0.2

[[done.subfeature]]
name="read subfeat"
priority=1.0
difficulty=0.2
