[project]
name="Project Manager"
version="0.0.1"
edition="0.0.0"

[[todo]]
name="upgrade system"
priority=0.3
difficulty=1.0

[[todo]]
name="redo get project config"
description="""
ways to implement
1) a project.toml be saved in the config folder wich hold the project structure and instead of the config.toml having the path to the status.toml it would hold to the name of the project and the project.toml
2) the status.toml could hold the subprojects and those would also be in the config.toml
"""
priority=0.1
difficulty=0.2

[[todo.subfeature]]
name="create subprojects"
priority=0.3
difficulty=0.8


[[todo]]
name="cli system"
priority=0.8
difficulty=0.5

[[todo]]
name="bake projects"
priority=0.9
difficulty=0.3

[[todo]]
name="project selector"
priority=0.2
difficulty=0.1

[[todo]]
name="upgrade project read"
priority=0.7
difficulty=0.1

[[done]]
name="read project"
priority=1.0
difficulty=0.2

[[done.subfeature]]
name="read subfeat"
priority=1.0
difficulty=0.2

[[done]]
name="project status"
priority=0.1
difficulty=0.1

[[done.subfeature]]
name="calculate % done"
priority=0.4
difficulty=0.1
