[done]
parse_files    = 1.0
design_project = 0.7
design_file    = 0.5
add_displayer  = 0.8
format_diplay  = 0.2

[todo]
add_git         = 0.1
notifications   = 0.4
redesign_config = 1.0
create_daemon   = 0.9
project_maker   = 0.2
refactor        = 9.0
