last_worked = ""

[desc]
name = "project_manager2"
priority = 0.0
difficulty = 0.0
version = "0.1.0"
edition = "0.1.18"
min_time = 30

[[tasks]]
done = false
project = ""

[tasks.desc]
name = "test feat"
priority = 1.0
difficulty = 1.0
version = "0.5.2"
edition = "0.1.0"
min_time = 30

[[tasks]]
done = false
project = ""

[tasks.desc]
name = "test feat"
priority = 1.0
difficulty = 1.0
version = "0.5.2"
edition = "0.1.0"
