[package]
name = "project_manager_client"
version = "0.1.1"
edition = "2021"

[dependencies]
dirs = "1.0"
rand = "0.8.5"
anyhow = "1.0.79"
thiserror = "1.0.57"
project_manager_api = {path = "../api"}

[dependencies.clap]
version  = "4.0"
features = ["derive"]
