[package]
name    = "project_manager_toml"
version = "0.0.0"
edition = "2021"

[dependencies]
toml = "0.7.2"
anyhow = "1.0.79"
thiserror = "1.0.57"

[dependencies.serde]
version  = "1.0"
features = ["derive"]
