[package]
name    = "project_manager_api"
version = "0.1.1"
edition = "2021"

[dependencies]
toml = "0.7.2"
dirs = "1.0"

[dependencies.serde]
version  = "1.0"
features = ["derive"]

[dependencies.clap]
version  = "4.0"
features = ["derive"]
